schema_version: 1

context:
  stubs_version: 0
  scipy_version: 1.18.0
  scipy_cap: 1.19.0
  python_min: "3.12"
  optype_min: 0.15.0
  optype_cap: 0.20.0
  mypy_version: 2.2.0

recipe:
  name: scipy-stubs-split
  version: ${{ scipy_version }}.${{ stubs_version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/scipy-stubs/scipy_stubs-${{ scipy_version }}.${{ stubs_version }}.tar.gz
  sha256: 761cb35106200c90a37034d3c8120d3899d673de1e5879d3a2ac1d6816c62327

build:
  number: 0

outputs:
  - package:
      name: scipy-stubs
    build:
      noarch: python
      script: pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python ${{ python_min }}.*
        - uv-build
        - pip
      run:
        - python >=${{ python_min }}
        - optype-numpy >=${{ optype_min }}, <${{ optype_cap }}
      run_constraints:
        - scipy >=${{ scipy_version }}, <${{ scipy_cap }}
    tests:
      - requirements:
          run:
            - python ${{ python_min }}.*
            - pip
        script:
          - pip check

  - package:
      name: scipy-typed
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - python >=${{ python_min }}
        - scipy ==${{ scipy_version }}
        - ${{ pin_subpackage('scipy-stubs', exact=True) }}
    tests:
      - python:
          imports:
            - scipy
      - files:
          recipe:
            - .mypyignore-extra
          source:
            - pyproject.toml
            - .mypyignore
        requirements:
          run:
            - python ${{ python_min }}.*
            - array-api-compat
            - pytest
            - matplotlib
            - mypy ==${{ mypy_version }}
        script:
          - stubtest --allowlist=.mypyignore --allowlist=.mypyignore-extra --ignore-disjoint-bases scipy

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Typing Stubs for SciPy
  description: The official type stubs for SciPy.
  homepage: https://github.com/scipy/scipy-stubs/
  repository: https://github.com/scipy/scipy-stubs/
  documentation: https://github.com/scipy/scipy-stubs?tab=readme-ov-file#scipy-stubs

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
  feedstock-name: scipy-stubs
